restylers:
  - name: prettier
    arguments: ['--write']
    include:
      - './*.{js,md}'
      - 'pages/**/*.js'
      - 'content/**/*.{js,md}'
      - 'src/**/*.js'
  - name: stylelint
    include:
      - 'src/**/*.css'
